CREATE TABLE interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  visitor_id UUID NOT NULL,
  event_name TEXT NOT NULL,
  path TEXT,
  details JSONB
);

ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can insert their own interactions"
  ON interactions FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Users can view their own interactions"
  ON interactions FOR SELECT
  USING (true); 